const rouletteTypes = {
  REMOVE_LAST_HISTORY_ITEM: "REMOVE_LAST_HISTORY_ITEM",
  ADD_HISTORY_ITEM: "ADD_HISTORY_ITEM",
  SET_BET_ZONE: "SET_BET_ZONE",
  CLEAN_ALL: "CLEAN_ALL_ROULETTE",
};

export default rouletteTypes;
