const settingsTypes = {
  CHANGE_BACKGROUND_COLOR: "CHANGE_BACKGROUND_COLOR",
  CHANGE_ZONE_BASE_AMOUNT: "CHANGE_ZONE_BASE_AMOUNT",
  CHANGE_NUMBER_BASE_AMOUNT: "CHANGE_NUMBER_BASE_AMOUNT",
  CHANGE_VISIBILITY: "CHANGE_VISIBILITY",
  RESET_TO_DEFAULT: "RESET_TO_DEFALT",
};

export default settingsTypes;
